---
- name: Create Service Account
  k8s:
    state: "{{ install_action | default('present') }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ filebeat.app }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ filebeat.app }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create cluster role binding
  k8s:
    state: "{{ install_action | default('present') }}"
    definition: "{{ lookup('template', 'filebeat-role-binding.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create config map for filebeat configuration file
  k8s:
    state: "{{ install_action | default('present') }}"
    definition: "{{ lookup('template', 'filebeat-config-map.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create daemon set for filebeat
  k8s:
    state: "{{ install_action | default('present') }}"
    definition: "{{ lookup('template', 'filebeat-daemon.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"
