- hosts: localhost
  connection: local
  tasks:
    - name: Create namespace for elk deployment
      k8s:
        name: "{{ namespace }}"
        state: present
        api_version: v1
        kind: Namespace
        kubeconfig: "{{ kubeconfig_path }}"

- hosts: localhost
  connection: local
  roles:
    - elasticsearch
