---
- name: Create config map for kibana configuration file
  k8s:
    state: "{{ install_action | default('present') }}"
    definition: "{{ lookup('template', 'kibana-config-map.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create deployment for kibana
  k8s:
    state: "{{ install_action | default('present') }}"
    definition: "{{ lookup('template', 'kibana-deployment.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create service for elasticsearch
  k8s:
    state: "{{ install_action | default('present') }}"
    definition: "{{ lookup('template', 'kibana-svc.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"
